name = "HeartBeats"
uuid = "83f3aa3b-6833-4362-9025-7697c9f4e58d"
authors = ["Clemens Brunner <clemens.brunner@gmail.com>"]
version = "0.1.0"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DSP = "0.7.4"
julia = "1"
